// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsActivityPhoto
{
    public int PhotoId { get; set; }

    public int ActivityId { get; set; }

    public string PhotoUrl { get; set; }

    public string Caption { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual KmsClassActivity Activity { get; set; }
}