// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsClassActivity
{
    public int ActivityId { get; set; }

    public int ClassId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateOnly? ActivityDate { get; set; }

    public int PostedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual KmsClass Class { get; set; }

    public virtual ICollection<KmsActivityPhoto> KmsActivityPhotos { get; set; } = new List<KmsActivityPhoto>();

    public virtual KmsTeacher PostedByNavigation { get; set; }

    public virtual KmsTeacher UpdatedByNavigation { get; set; }
}