// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsClassStudent
{
    public int ClassId { get; set; }

    public int StudentId { get; set; }

    public DateTime? EnrolledAt { get; set; }

    public int? EnrolledBy { get; set; }

    public virtual KmsClass Class { get; set; }

    public virtual KmsUser EnrolledByNavigation { get; set; }

    public virtual KmsStudent Student { get; set; }
}