// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsKitchenSample
{
    public int SampleId { get; set; }

    public int? MenuId { get; set; }

    public DateOnly? SampleDate { get; set; }

    public TimeOnly? SampleTime { get; set; }

    public int? StoredBy { get; set; }

    public DateTime? DisposalTime { get; set; }

    public string Note { get; set; }

    public virtual KmsMenu Menu { get; set; }
}