// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsMenu
{
    public int MenuId { get; set; }

    public int? ClassId { get; set; }

    public DateOnly MenuDate { get; set; }

    public string MealType { get; set; }

    public string MenuContent { get; set; }

    public int? Calories { get; set; }

    public string Allergens { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public string Source { get; set; }

    public string SupplierName { get; set; }

    public int? PreparedBy { get; set; }

    public virtual KmsClass Class { get; set; }

    public virtual KmsUser CreatedByNavigation { get; set; }

    public virtual ICollection<KmsKitchenSample> KmsKitchenSamples { get; set; } = new List<KmsKitchenSample>();

    public virtual KmsUser UpdatedByNavigation { get; set; }
}