// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsNotification
{
    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public string Type { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string RelatedEntityType { get; set; }

    public int? RelatedEntityId { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual KmsUser User { get; set; }
}