// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsSemester
{
    public int SemesterId { get; set; }

    public int SchoolYearId { get; set; }

    public string SemesterName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual KmsSchoolYear SchoolYear { get; set; }
}