// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KMS.Repository.Entities;

public partial class KmsTuitionItem
{
    public int ItemId { get; set; }

    public int TemplateId { get; set; }

    public string ItemName { get; set; }

    public decimal Amount { get; set; }

    public int? ItemOrder { get; set; }

    public virtual KmsTuitionTemplate Template { get; set; }
}